id: D57E5CDFF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:49:14+00:00'
last_modified: '2022-05-30T06:40:31.589620+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    746b:
      image_group_id: I1PD95961
      title: བཀྲ་ཤིས་ཀྱི་ཚིགས་སུ་བཅད་པ།
      total_pages: 1880
      order: 116
      base_file: 746b.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
