id: PCF92BC0E
initial_creation_type: ocr
source_metadata:
  volumes:
    b594d40a174e4361bf7249f60bb1a160:
      base_file: v116.txt
      image_group_id: I1PD95961
      title: བཀྲ་ཤིས་ཀྱི་ཚིགས་སུ་བཅད་པ།
      total_pages: 1880
      volume_number: 116
